### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by samguyjones** [pardeike/RimGPT#4]
I'd really like to log the requests that are going to ChatGPT for some odd responses like:

- I got about five comments about how we'd tamed alpacas when there were no alpacas in the area.
- A couple times a narrator has commented on someone's death when nobody's died.
- The narrator frequently misgenders people.

Again, this is so cool!

**Comment by pardeike** [comment]
Each request to the AI is in this form:

You play the role of [X]. You will get all things that happened in the game plus a summary of things that happened so far.
You respond according to your role with two things:
1) something to say
2) a summar of everything so far that will be send to you in the next request

As you can see, the summary can remember things. That can be either a misunderstanding or outdated but that's the way this works. There is no good way to do this and I accept the occasional wrongdoing. It will disappear as soon as a lot of new stuff happens. The problem you describe usually only appears with little or nothing new happens in the game.

The narrator only gets textual information from the mod. It therefore can easily mix up who is who and does not know the gender of people either. The textual information I gather is due to keeping costs low limited to "Colonist X verb Y" or "Raider A verb B" (basically the pawns log) plus all the notes on the screen and all the internal thoughts pawns have plus a few things I already forgot. It is impractical to send everything.
